### ISSUE TITLE
Undefined variable: context

### ISSUE THREAD

**Issue by grunch** [joaodealmeida/woocommerce-gateway-lightning#1]
Hi, I'm getting this notice 

PHP Notice:  Undefined variable: context in /var/www/html/wp-content/plugins/woocommerce-gateway-lightning-master/Lnd_wrapper.php on line 148

https://github.com/joaodealmeida/woocommerce-gateway-lightning/blob/c95d2d1eda190578b2906bb5dcb30eaa62d29bea/Lnd_wrapper.php#L148

**Comment by grunch** [comment]
PR: https://github.com/joaodealmeida/woocommerce-gateway-lightning/pull/2

**Comment by joaodealmeida** [comment]
Merged.
