### ISSUE TITLE
Time, RHASH & Amounts not showing in "Order Received" page (after Woocommerce update)

### ISSUE THREAD

**Issue by highvolt4ge** [joaodealmeida/woocommerce-gateway-lightning#10]
After updating to Woocommerce Version 3.4.0 the "Order Received" page shows timestamps and amounts wrongly. Using Version 0.1.0 of Gateway-Lightning.

Version 3.4.0 - https://github.com/woocommerce/woocommerce/blob/master/CHANGELOG.txt

See picture below. 
![ltc_woocommerce](https://user-images.githubusercontent.com/39427937/40561111-a9bf6b22-6064-11e8-9eae-391a70eeea66.png)

**Comment by highvolt4ge** [comment]
Seems like getInvoiceInfoFromHash can't get the correct information? No errors / odd lines in lnd.log. Gateway-Lightning created the invoice succesfully and user was able to pay it without any problems.

Notice: Undefined property: stdClass::$settle_date in plugins/woocommerce-gateway-lightning-master/templates/completed.php on line 8
Thu, 01 Jan 1970 00:00:00 +0000
LIGHTNING RHASH:

Notice: Undefined property: stdClass::$r_hash in plugins/woocommerce-gateway-lightning-master/templates/completed.php on line 11
INVOICE AMOUNT:

Notice: Undefined property: stdClass::$value in plugins/woocommerce-gateway-lightning-master/templates/completed.php on line 14

**Comment by githorray** [comment]
I noticed this today too after doing a test order.

**Comment by joaodealmeida** [comment]
I'll take a look this weekend and report back.

**Comment by highvolt4ge** [comment]
Alright, hit me with message if you need help testing in LTC LN.

**Comment by joaodealmeida** [comment]
Should be fixed with PR #13
