### ISSUE TITLE
"Error: Lightning Node is not reachable at this time. Please contact the store administrator."

### ISSUE THREAD

**Issue by aqualan3** [joaodealmeida/woocommerce-gateway-lightning#6]
PHP7.0, Debian 8, nginx/1.10.3, WordPress 4.9.5, LND 0.4.1-beta commit=8af80bfc5cdebcd323ed2a50ea0497df6e9bc6e4.

When I click "Proceed to Lightning Payment" at checkout I get following errors:

"Error: Lightning Node is not reachable at this time. Please contact the store administrator."

Notice: Undefined variable: context in wp-content/plugins/woocommerce-gateway-lightning-master/Lnd_wrapper.php on line 148

Warning: First parameter must either be an object or the name of an existing class in wp-content/plugins/woocommerce-gateway-lightning-master/woocommerce-gateway-lightning.php on line 142

Warning: First parameter must either be an object or the name of an existing class in wp-content/plugins/woocommerce-gateway-lightning-master/woocommerce-gateway-lightning.php on line 147

Orders go throug though, I can see em in WooCommerce Orders-section, Status: Pending Payment.

**Comment by joaodealmeida** [comment]
Hello, are you using invoice macaroon or admin macaroon ?

**Comment by aqualan3** [comment]
I'm using admin macaroon. Acquired the hex with xxd -ps -u -c 1000.

**Comment by joaodealmeida** [comment]
Are you using --restlisten=0.0.0.0:8080 flag?

Also, does your endpoint looks like 'https://SERVERIP:PORT ?

**Comment by aqualan3** [comment]
Im using restlisten=0.0.0.0:10111. Endpoint is https://SERVERIP:10111

**Comment by joaodealmeida** [comment]
Did you copy your tls.cert file to the same path you have as input in the plugin configuration?
Are you using rpclisten flag at the same time ?

**Comment by aqualan3** [comment]
I have copied tls.cert to /home/wp/wp-content/plugins/woocommerce-gateway-lightning-master/tls. I have rpclisten flag enabled but using different port.

When I click "Proceed to Lightning Payment" I can see in lnd.log "2018/05/04 20:24:42 http: TLS handshake error from SERVERIP:44388: EOF" error, which is odd because i'm using https and port is so random.

**Comment by joaodealmeida** [comment]
I believe LND has a bug on certificates that doesn't allow you to have both restlisten and rcplisten enabled.

1. Stop lnd and remove tls.cert and tls.key
2. start lnd without rpclisten flag
3. Move new tls.cert to the plugin directory and make sure the path is correct on the plugin configs.
4. Try to place an order

**Comment by aqualan3** [comment]
Thanks for the help! I was running 2 instances of LND, had to shutdown both and start the one using woocommerce first. After that everything worked fine :)
