### ISSUE TITLE
LND connect Problem 

### ISSUE THREAD

**Issue by leblitzdick** [joaodealmeida/woocommerce-gateway-lightning#7]
Hi João,

so here i am, you can take a look at my lnd.conf: 

[Application Options]
externalip=85.25.255.147
restlisten=localhost:8080
listen=0.0.0.0:9735
rpclisten=localhost:10009
#debuglevel=trace, debug, info, warn, error, critical
debuglevel=info
debughtlc=true
maxpendingchannels=10
alias=bitcoin-lightning.de
color=#8DB335

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind

[autopilot]
autopilot.active=1
autopilot.maxchannels=50
autopilot.allocation=0.6

thanks
Matthias

**Comment by joaodealmeida** [comment]
I believe there is a restlisten & rpclisten bug on LND if used at the same time. Could you please disable the rpclisten flag while testing?

Also, is the wordpress server the same as the LND machine ?

**Comment by leblitzdick** [comment]
Yes the same machine.

I change the config to this:

[Application Options]
externalip=85.25.255.147
restlisten=localhost:8080
#listen=0.0.0.0:9735  <-- don't need this, default                                                                                     
#rpclisten=localhost:10009                                                                                                                  

and restart LND, but still the same Problem

**Comment by leblitzdick** [comment]
Good Morning,
sometimes a little bit sleep will solve the Problem :-)
My problem solved! I checked the hex admin.macaron, and there was a converting fairlure!!
Now the Lightning invoice appearance.

thanks

if the shop is online, you will get a free gift ;-)

**Comment by nflaig** [comment]
@leblitzdick I know this Issue is closed but how exactly did you fix your problem? I am not able to use restlisten and rpclisten at the same time for some reason. I am using `lnd v0.5.1-beta`.

**Comment by joaodealmeida** [comment]
Are you able to use it if you disable rpclisten?

**Comment by nflaig** [comment]
Yes it works if I disable rpclisten but I found a workaround which allows to have both enabled.

This did not work:
> restlisten=localhost:8080
rpclisten=0.0.0.0:10009

This works:
> restlisten=localhost:8080
rpclisten=localhost:10008
rpclisten=0.0.0.0:10009

I think the problem is that adding `rpclisten=0.0.0.0:10009` overwrites the default rpclisten and that causes problems with restlisten. I am not to sure if it is a bug or intended but adding `rpclisten=localhost:10008` solved it.
